name: de4js
title: JavaScript Online Deobfuscator(js在线解密反混淆)
description: JavaScript Deobfuscator|Beautify(美化)|Purify(净化)|Encrypt(加密)|Decrypt(解密)|Uglify(混淆)|Online(在线)
version: 1.12.0
author: Zzbaivong
author_email: Zzbaivong@gmail.com
url: https://lelinhtinh.github.io
baseurl: /de4js
repository: lelinhtinh/de4js
license: MIT

theme: jekyll-theme-hacker
show_downloads: false
google_analytics: 
sass:
  style: compressed

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "package.json",
    "package-lock.json",
    "Dockerfile",
    "docker-compose.yml",
    "docker-entrypoint.sh",
    "workbox-config.js"
  ]
incremental: false

environment: production
